config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  
  resources :students, except: [ :destroy ]

  get 'about', to: 'pages#about'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'courses/:id/enroll', to: 'student_courses#create', as: 'course_enroll'
  get 'courses/new', to: 'courses#new'
  post 'courses', to: 'courses#create'
  get 'courses/:id', to: 'courses#show', as: 'course'
  get 'courses/:id/edit', to: 'courses#edit', as: 'edit_course'
  match 'courses/:id', via: [:put, :patch], to: 'courses#update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  validates :short_name, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 15 }
  validates :description, presence: true, length: { minimum: 10, maximum: 255 }

  has_many :student_courses
  has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord

  before_save { self.email = email.downcase }

  has_secure_password

  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i  
  validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false },  format: { with: VALID_EMAIL_REGEX } 

  has_many :student_courses
  has_many :courses, through: :student_courses

end

app/models/student_course.rb
class StudentCourse < ApplicationRecord 

  belongs_to :student 
  belongs_to :course

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?
  
  before_action :require_user

  def current_user
    @current_user ||= Student.find(session[:student_id]) if session[:student_id]
  end

  def logged_in? 
    !!current_user
  end

  def require_user
    if !logged_in? 
      flash[:error] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  skip_before_action :require_user, only: [ :index ]

  before_action :set_course, only: [ :show, :update, :edit ]

  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create 
    @course = Course.new(course_params)
    if @course.save 
      flash[:notice] = "The course #{@course.name} has been created successfully"
      redirect_to root_path
    else
      render 'new'
    end
  end
  def show 
  end

  def edit 
  end

  def update 
    if @course.update(course_params)
      flash[:notice] = "You have update the course successfully"
      redirect_to @course
    else
      render 'edit'
    end

  end

  private 

  def course_params
    params.require(:course).permit(:name, :short_name, :description)
  end

  def set_course
    @course = Course.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController 

  skip_before_action :require_user

  def about
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :require_user, except: [ :destroy ]

  def new 
  end

  def create
    student = Student.find_by(email: params[:session][:email])
    if student and student.authenticate(params[:session][:password])
      session[:student_id] = student.id
      flash[:notice] = "You have successfully logged in"
      redirect_to student
    else
      flash.now[:error] = "Something was wrong with your login informations"
      render 'new'
    end
  end

  def destroy
    session[:student_id] = nil
    flash[:notice] = "You have successfully logged out"
    redirect_to root_path
  end

end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController

  def create
    course = Course.find(params[:id])
    unless !course or current_user.courses.include?(course)
      current_user.courses << course
      flash[:notice] = "You have successfully enrolled in #{course.name}"
      redirect_to current_user
    else
      flash[:error] = "Something was wrong with your enrollment"
      redirect_to root_path
    end
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :set_student, only: [ :show, :edit, :update ]
  before_action :require_same_student, only: [ :edit, :update ]

  skip_before_action :require_user, only: [ :new, :create ]

  def index 
    @students = Student.all
  end

  def new 
    @student = Student.new
  end

  def create
    @student = Student.new student_params
    if @student.save
      flash[:notice] = "You have successfully signed up"
      redirect_to login_path
    else
      render 'new'
    end
  end

  def update 
    if @student.update(student_params)
      flash[:notice] = "You have successfully updated your profile"
      redirect_to @student
    else
      render 'new'
    end

  end

  def show 
  end

  def edit 
  end

  private 

  def student_params 
    params.require(:student).permit(:name, :email, :password, :password_confirmation)
  end
  
  def set_student
    @student = Student.find(params[:id])
  end
  
  def require_same_student
    if current_user != @student 
      flash[:error] = "You can only edit your own profile"
      redirect_to student_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<div class="col s12 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= course.short_name %>: <%= course.name %> </span>
        <p><%= course.description %></p>
      </div>
      <div class="card-action overflow-hidden">
        <% if logged_in? and !current_user.courses.include?(course) %>
          <%= link_to "Enroll", course_enroll_path(course), method: :post %>
        <% else %>
          <span class="new badge" data-badge-caption="">Already enrolled</span>
        <% end %>
        <% if logged_in? %>
          <%= link_to "Edit", edit_course_path(course) %>
        <% end %>
        <% if request.path != course_path(course) %>
          <%= link_to "More infos", course %>
        <% end %>
      </div>
    </div>
  </div>

app/views/courses/_form.html.erb
<%= render 'shared/errors', obj: @course %>

<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <div class="row">
          <%= form_for @course, html: { class: "col s12" } do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :name, placeholder: "Enter the course name", autofocuse: true %>
                <%= f.label :name, class:"active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :short_name, placeholder: "Enter the course unique code ( Example CS111)" %>
                <%= f.label :short_name, class:"active" %>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.text_area :description, placeholder: "Enter description", class: "materialize-textarea" %>
                <%= f.label :description, class:"active" %>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.button(@course.new_record? ? 'New course <i class="material-icons right">arrow_forward</i>'.html_safe : 'Submit changes <i class="material-icons right">arrow_forward</i>'.html_safe, class:"btn waves-effect waves-light #{@course.new_record? ? 'green' : 'orange'} right") %>
              </div>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/courses/edit.html.erb
<div class="row">
  <div class="col s12 center-align">
    <h3>Edit course <%= @course.name %></h3>
    <small>For demo purposes only</small>
  </div>
</div>

<%= render 'form' %>

app/views/courses/index.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align">Course listing</h3>
  </div>
</div>

<% if logged_in? %>
  <%= link_to "<i class='material-icons left'>add</i>Add new course".html_safe, courses_new_path, class: " btn-large waves-effect waves-light green" %>
  <small>(for demo purposes only)</small>
<% end %>
<div class="row">
  <% if @courses.any? %>
    <%= render @courses %>
  <% else %>
    <p>There currently is no course available, please <%= link_to "log in", login_path %> or <%= link_to "sign up", new_student_path %> to add a course </p>
  <% end %>  
</div>

app/views/courses/new.html.erb
<div class="row">
  <div class="col s12 center-align">
    <h3>New course </h3>
    <small>For demo purposes only</small>
  </div>
</div>

<%= render 'form' %>

app/views/courses/show.html.erb
<%= render @course %>

<% unless @course.students.empty? %>
  <ul class="collection with-header">
    <li class="collection-header"><h4>Students enrolled in this course</h4></li>
    <% @course.students.each do |student| %>
      <li class="collection-item">
        <div>
          <%= student.email %>
          <%= link_to '<i class="material-icons small">pageview</i>'.html_safe, student, class: "secondary-content" %>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_account_navigation.html.erb
<% if logged_in? %>
    <li><%= link_to "Logout", logout_path, method: :delete %></li>
    <li><%= link_to "View your profile", current_user %></li>
  <% else %>
    <li><%= link_to "Login", login_path %></li>
    <li><%= link_to "Sign up", new_student_path %> </li>
  <% end %>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Redi University</h5>
        <p class="grey-text text-lighten-4">The future of development training.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Contact us</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2021 Redi University
    <a class="grey-text text-lighten-4 right" href="#!">About</a>
    </div>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |type, message| %>
  <div class="container">
    <div class="row sign-up-form">
      <div class="col s12 m12 l12">
        <div class="card-panel <%= type=='notice' ? 'green' : 'red' %> lighten-2 fade-out-target" >
          <span class="white-text">
            <%= message %>
          </span>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/layouts/_navigation.html.erb
<ul id="dropdown1" class="dropdown-content">
  <%= render 'layouts/account_navigation' %>
</ul>
<ul id="dropdown2" class="dropdown-content">
  <%= render 'layouts/account_navigation' %>
</ul>
<nav>
  <div class="container">
    <div class="nav-wrapper">
      <%= link_to "Redi University", root_path, class: "brand-logo" %>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to 'Courses', root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Students", students_path %></li>
        <% end %>
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Account<i class="material-icons right">arrow_drop_down</i></a></li>
      </ul>
    </div>
  </div>
</nav>
<ul class="sidenav" id="mobile-demo">
    <li><%= link_to 'Courses', root_path %></li>
    <% if logged_in? %>
      <li><%= link_to "Students", students_path %></li>
    <% end %>
    <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Redi University</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
      <%= render 'layouts/messages' %>
    </header>
    <main class="container">
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Hi this is the about page</h1>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="container">
    <div class="row sign-up-form">
      <div class="col s12 m12 l12">
        <div class="card-panel red lighten-2">
          <span class="white-text">
            <strong><%= pluralize(obj.errors.count, 'error') %></strong>
            prohibited your form from getting submitted
            <ul>
              <% obj.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/students/_form.html.erb
<%= render 'shared/errors', obj: @student %>

<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="header"><%= @student.new_record? ? 'Sign up!' : 'Edit your profile' %></h3>
        <div class="row">
          <%= form_for @student, html: { class: "col s12" } do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :name, placeholder: "Enter your full name", autofocuse: true %>
                <%= f.label :name, class:"active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.email_field :email, placeholder: "Enter your email address" %>
                <%= f.label :email, class:"active" %>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.password_field :password, placeholder: "Choose a password" %>
                <%= f.label :password, class:"active" %>
              </div>
            </div>
            <div class="row">
              <div class="input-field col s12">
                <%= f.password_field :password_confirmation, placeholder: "Confirm your password" %>
                <%= f.label :password_confirmation, class:"active" %>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.button(@student.new_record? ? 'Sign up <i class="material-icons right">arrow_forward</i>'.html_safe : 'Submit changes <i class="material-icons right">arrow_forward</i>'.html_safe, class:"btn waves-effect waves-light orange right") %>
              </div>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/_student.html.erb
<div class="col s6 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title">Name: <%= student.name %> </span>
        <p>Email: <%= student.email %> </p>
        <p>Course enrollments: 
          <% if student.courses.empty? %>
            None
          <% else %>
            <ul>
              <% student.courses.each do |course| %>
                <li> <%= course.name %> </li>
              <% end %>
            </ul>
          <% end %>
        </p>
      </div>
      <% unless request.path == student_path(student) %>
        <div class="card-action">
          <%= link_to "View profile", student %>
        </div>
      <% end %>
    </div>
  </div>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align">Students directory</h3>
  </div>
</div>

<div class="row">
  <%= render @students %>  
</div>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<%= render @student %>

<% if current_user == @student %>
  <%= link_to 'Edit your profile <i class="material-icons right">edit</i>'.html_safe, edit_student_path(@student), class: "waves-effect waves-light btn orange" %>
<% end %>